products/urls.py
from django.urls import path
from products.views import (ProductListView,
                            ProductDetailSlugView,
                            )
app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view() , name = 'product_list') ,
    path('<slug>' , ProductDetailSlugView.as_view() , name = 'productSlugDetail') ,
    # path('products-fbv/<productId>' , product_detail_view),
    # path('products-fbv' , product_list_view) ,
    # path('featured' , ProductFeaturedListView.as_view()),
    # path('featured/<pk>' , ProductDetailFeaturedView.as_view()) ,
]

projectNew/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path , include
from projectNew.views import (about_us ,
                              contact_page ,
                              login_page ,
                              register_page ,
                              home_page,
                              )


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name ='home_page'),
    path('about_us/', about_us, name='about_us'),
    path('contact_us/', contact_page, name ='contact_us'),
    path('login/', login_page, name ='login') ,
    path('register/', register_page, name  ='register'),
    path('products/' , include('products.urls' , namespace='products'))
    #path('products/<pk>' , ProductDetailView.as_view()) ,

]

if settings.DEBUG :

    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}


 <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<!-- Bootstrap -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
{#  <link rel="stylesheet" href="{% static "" %}">#}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<title>Title</title>

templates/base/js.html
{% load static %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

templates/base/nav.html
{% url "home_page"  as homepage %}
{% url "login"  as loginpage %}
{% url "register"  as registerpage %}
{% url "about_us"  as aboutpage %}
{% url "contact_us"  as contactpage %}
{% url "products:product_list"  as productpage %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">{{ title }}</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{% if request.path == homepage %} active {% endif %}"><a href="{{ homepage }}">Home <span class="sr-only">(current)</span></a></li>
        <li  class="{% if request.path == productpage %} active {% endif %}"><a href="{{ productpage }}">product</a></li>
          <li   class="{% if request.path == aboutpage %} active {% endif %}"><a href="{{aboutpage}}">about us</a></li>
          <li   class="{% if request.path == contactpage %} active {% endif %}"><a href="{{contactpage}}">contact us</a></li>
        {% if not request.user.is_authenticated %}

          <li  class="{% if request.path == loginpage %} active {% endif %}"><a href="{{ loginpage}}">Login</a></li>
          <li  class="{% if request.path == registerpage %} active {% endif %}"><a href="{{registerpage}}">Register</a></li>
            {% else %}
          <li  ><a href="/admin/logout/">logout</a></li>
        {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>